METAS_MUNICIPIOS = {
  "resumen": {
    "PEÑÓN BLANCO": 4451,
    "SANTA CLARA": 20910,
    "TOPIA": 10378,
    "SÚCHIL": 11896,
    "SAN BERNARDO": 758,
    "SAN PEDRO DEL GALLO": 2456,
    "GUANACEVÍ": 3918,
    "POANAS": 10172,
    "TEPEHUANES": 8058,
    "HIDALGO": 1303,
    "INDÉ": 1529,
    "OCAMPO": 2499,
    "CONETO DE COMONFORT": 1555,
    "RODEO": 4884,
    "NOMBRE DE DIOS": 7518,
    "CANATLÁN": 12095,
    "CUENCAMÉ": 14276,
    "LERDO": 72499,
    "EL ORO": 3612,
    "PÁNUCO DE CORONADO": 4903,
    "OTÁEZ": 2074,
    "GENERAL SIMÓN BOLÍVAR": 3780,
    "CANELAS": 1888,
    "NUEVO IDEAL": 11967,
    "GÓMEZ PALACIO": 163112,
    "SAN DIMAS": 6956,
    "MEZQUITAL": 25853,
    "PUEBLO NUEVO": 23525,
    "SAN JUAN DE GUADALUPE": 1837,
    "DURANGO": 299906,
    "MAPIMÍ": 11713,
    "NAZAS": 4988,
    "GUADALUPE VICTORIA": 15026,
    "TAMAZULA": 4520,
    "TLAHUALILO": 4091,
    "SAN LUIS DEL CORDERO": 647,
    "SAN JUAN DEL RÍO": 811,
    "VICENTE GUERRERO": 4632,
    "SANTIAGO PAPASQUIARO": 3045
  },
  "g611": {
    "SAN PEDRO DEL GALLO": 0,
    "TOPIA": 0,
    "TEPEHUANES": 0,
    "SAN JUAN DE GUADALUPE": 0,
    "CANELAS": 0,
    "SÚCHIL": 0,
    "OTÁEZ": 0,
    "POANAS": 0,
    "CUENCAMÉ": 0,
    "NOMBRE DE DIOS": 0,
    "INDÉ": 0,
    "SAN DIMAS": 0,
    "MEZQUITAL": 0,
    "PUEBLO NUEVO": 0,
    "GENERAL SIMÓN BOLÍVAR": 0,
    "HIDALGO": 0,
    "MAPIMÍ": 0,
    "CONETO DE COMONFORT": 0,
    "NAZAS": 0,
    "CANATLÁN": 0,
    "OCAMPO": 0,
    "EL ORO": 0,
    "RODEO": 0,
    "DURANGO": 0,
    "LERDO": 0,
    "PÁNUCO DE CORONADO": 0,
    "GÓMEZ PALACIO": 0,
    "NUEVO IDEAL": 0,
    "TAMAZULA": 0,
    "TLAHUALILO": 0,
    "GUADALUPE VICTORIA": 0,
    "SAN LUIS DEL CORDERO": 0,
    "SAN JUAN DEL RÍO": 0,
    "VICENTE GUERRERO": 0,
    "SANTIAGO PAPASQUIARO": 0
  },
  "g1": {
    "SAN BERNARDO": 0,
    "SAN PEDRO DEL GALLO": 0,
    "HIDALGO": 0,
    "TEPEHUANES": 0,
    "GUANACEVÍ": 0,
    "POANAS": 0,
    "OCAMPO": 0,
    "INDÉ": 0,
    "NOMBRE DE DIOS": 0,
    "CONETO DE COMONFORT": 0,
    "EL ORO": 0,
    "PÁNUCO DE CORONADO": 0,
    "CUENCAMÉ": 0,
    "PUEBLO NUEVO": 0,
    "MEZQUITAL": 0,
    "RODEO": 0,
    "CANELAS": 0,
    "GENERAL SIMÓN BOLÍVAR": 0,
    "CANATLÁN": 0,
    "SAN DIMAS": 0,
    "NAZAS": 0,
    "LERDO": 0,
    "DURANGO": 0,
    "MAPIMÍ": 0,
    "OTÁEZ": 0,
    "SAN JUAN DE GUADALUPE": 0,
    "GÓMEZ PALACIO": 0,
    "NUEVO IDEAL": 0,
    "GUADALUPE VICTORIA": 0,
    "TAMAZULA": 0,
    "TLAHUALILO": 0,
    "SAN LUIS DEL CORDERO": 0,
    "SAN JUAN DEL RÍO": 0,
    "VICENTE GUERRERO": 0,
    "SANTIAGO PAPASQUIARO": 0
  },
  "g18": {
    "TOPIA": 0,
    "SAN PEDRO DEL GALLO": 0,
    "TEPEHUANES": 0,
    "GUANACEVÍ": 0,
    "INDÉ": 0,
    "OCAMPO": 0,
    "POANAS": 0,
    "EL ORO": 0,
    "CANATLÁN": 0,
    "MEZQUITAL": 0,
    "OTÁEZ": 0,
    "PUEBLO NUEVO": 0,
    "HIDALGO": 0,
    "CUENCAMÉ": 0,
    "NOMBRE DE DIOS": 0,
    "RODEO": 0,
    "DURANGO": 0,
    "CANELAS": 0,
    "CONETO DE COMONFORT": 0,
    "LERDO": 0,
    "GÓMEZ PALACIO": 0,
    "SAN DIMAS": 0,
    "GUADALUPE VICTORIA": 0,
    "PÁNUCO DE CORONADO": 0,
    "GENERAL SIMÓN BOLÍVAR": 0,
    "NAZAS": 0,
    "MAPIMÍ": 0,
    "NUEVO IDEAL": 0,
    "TAMAZULA": 0,
    "SAN LUIS DEL CORDERO": 0,
    "SAN JUAN DE GUADALUPE": 0,
    "VICENTE GUERRERO": 0,
    "TLAHUALILO": 0,
    "SAN JUAN DEL RÍO": 0,
    "SANTIAGO PAPASQUIARO": 0
  },
  "grez": {
    "SÚCHIL": 0,
    "GUANACEVÍ": 0,
    "TEPEHUANES": 0,
    "SAN JUAN DE GUADALUPE": 0,
    "CUENCAMÉ": 0,
    "GENERAL SIMÓN BOLÍVAR": 0,
    "CONETO DE COMONFORT": 0,
    "SAN BERNARDO": 0,
    "INDÉ": 0,
    "OCAMPO": 0,
    "NAZAS": 0,
    "HIDALGO": 0,
    "EL ORO": 0,
    "POANAS": 0,
    "NUEVO IDEAL": 0,
    "LERDO": 0,
    "CANELAS": 0,
    "CANATLÁN": 0,
    "OTÁEZ": 0,
    "MAPIMÍ": 0,
    "NOMBRE DE DIOS": 0,
    "RODEO": 0,
    "SAN LUIS DEL CORDERO": 0,
    "GÓMEZ PALACIO": 0,
    "PUEBLO NUEVO": 0,
    "MEZQUITAL": 0,
    "SAN DIMAS": 0,
    "DURANGO": 0,
    "TLAHUALILO": 0,
    "PÁNUCO DE CORONADO": 0,
    "TAMAZULA": 0,
    "GUADALUPE VICTORIA": 0,
    "SAN JUAN DEL RÍO": 0,
    "VICENTE GUERRERO": 0,
    "SANTIAGO PAPASQUIARO": 0
  },
  "g1319": {
    "SANTA CLARA": 0,
    "POANAS": 0,
    "RODEO": 0,
    "PÁNUCO DE CORONADO": 0,
    "HIDALGO": 0,
    "MEZQUITAL": 0,
    "CONETO DE COMONFORT": 0,
    "INDÉ": 0,
    "SAN JUAN DEL RÍO": 0,
    "TEPEHUANES": 0,
    "NOMBRE DE DIOS": 0,
    "OCAMPO": 0,
    "GUANACEVÍ": 0,
    "CUENCAMÉ": 0,
    "OTÁEZ": 0,
    "GÓMEZ PALACIO": 0,
    "PUEBLO NUEVO": 0,
    "DURANGO": 0,
    "LERDO": 0,
    "SAN DIMAS": 0,
    "NUEVO IDEAL": 0,
    "EL ORO": 0,
    "CANATLÁN": 0,
    "VICENTE GUERRERO": 0,
    "CANELAS": 0,
    "GENERAL SIMÓN BOLÍVAR": 0,
    "SAN PEDRO DEL GALLO": 0,
    "MAPIMÍ": 0,
    "TAMAZULA": 0,
    "GUADALUPE VICTORIA": 0,
    "SAN JUAN DE GUADALUPE": 0,
    "TLAHUALILO": 0,
    "NAZAS": 0,
    "SANTIAGO PAPASQUIARO": 0,
    "SAN LUIS DEL CORDERO": 0
  },
  "g2039": {
    "RODEO": 0,
    "SANTA CLARA": 0,
    "SÚCHIL": 0,
    "PÁNUCO DE CORONADO": 0,
    "HIDALGO": 0,
    "NOMBRE DE DIOS": 0,
    "OCAMPO": 0,
    "CANATLÁN": 0,
    "LERDO": 0,
    "SAN PEDRO DEL GALLO": 0,
    "GUANACEVÍ": 0,
    "CONETO DE COMONFORT": 0,
    "INDÉ": 0,
    "MEZQUITAL": 0,
    "OTÁEZ": 0,
    "TEPEHUANES": 0,
    "EL ORO": 0,
    "NUEVO IDEAL": 0,
    "SAN DIMAS": 0,
    "GENERAL SIMÓN BOLÍVAR": 0,
    "CANELAS": 0,
    "DURANGO": 0,
    "PUEBLO NUEVO": 0,
    "SAN JUAN DEL RÍO": 0,
    "GÓMEZ PALACIO": 0,
    "CUENCAMÉ": 0,
    "GUADALUPE VICTORIA": 0,
    "SAN JUAN DE GUADALUPE": 0,
    "MAPIMÍ": 0,
    "SAN LUIS DEL CORDERO": 0,
    "TAMAZULA": 0,
    "TLAHUALILO": 0,
    "NAZAS": 0,
    "VICENTE GUERRERO": 0,
    "SANTIAGO PAPASQUIARO": 0
  },
  "g4049": {
    "POANAS": 0,
    "SAN BERNARDO": 0,
    "RODEO": 0,
    "CONETO DE COMONFORT": 0,
    "HIDALGO": 0,
    "SANTA CLARA": 0,
    "SAN DIMAS": 0,
    "CANATLÁN": 0,
    "NOMBRE DE DIOS": 0,
    "SÚCHIL": 0,
    "GUANACEVÍ": 0,
    "PUEBLO NUEVO": 0,
    "MEZQUITAL": 0,
    "LERDO": 0,
    "INDÉ": 0,
    "NUEVO IDEAL": 0,
    "TEPEHUANES": 0,
    "OTÁEZ": 0,
    "OCAMPO": 0,
    "CUENCAMÉ": 0,
    "EL ORO": 0,
    "GÓMEZ PALACIO": 0,
    "SAN JUAN DE GUADALUPE": 0,
    "DURANGO": 0,
    "GENERAL SIMÓN BOLÍVAR": 0,
    "GUADALUPE VICTORIA": 0,
    "MAPIMÍ": 0,
    "CANELAS": 0,
    "TAMAZULA": 0,
    "SAN LUIS DEL CORDERO": 0,
    "SAN JUAN DEL RÍO": 0,
    "NAZAS": 0,
    "TLAHUALILO": 0,
    "VICENTE GUERRERO": 0,
    "SANTIAGO PAPASQUIARO": 0
  }
}